
export const SET_USER_INFO = 'SET_USER_INFO'
export const CLEAR_USER_INFO = 'CLEAR_USER_INFO'
export const USER_CITY_LIST = 'USER_CITY_LIST'
export const SET_USER_LOCATION = 'SET_USER_LOCATION'
export const SET_WECHAT_USER_INFO = 'SET_WECHAT_USER_INFO'
